version = 1

[install]
bun.pkg-path = "bun"

[hook]
on-activate = '''
  export PORT=3000
  echo "Value of PORT variable is $PORT"
  bun install
'''

[services]
express.command = "bun server.ts --watch"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
