version: 2
updates:

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  labels:
    - "team-developer-support"
  open-pull-requests-limit: 1
  commit-message:
      prefix: "chore"
      include: "scope"
  groups:
    all:
      patterns:
        - "*"
