version = 1
#
# This is a flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1), manifest.toml(1) for more information.
#

[install]
xquartz.pkg-path = "xquartz"
quartz-wm.pkg-path = "quartz-wm"
xterm.pkg-path = "xterm"

[vars]
DISPLAY=":0"

[services.xquartz]
command = "xquartz"

[services.quartz-wm]
command = "quartz-wm"

[profile]
bash = """
  alias ssh="ssh -XY"
"""

zsh = """
  alias ssh="ssh -XY"
"""

[options]
systems = ["aarch64-darwin", "x86_64-darwin"]


