version = 1

[install]
colima.pkg-path = "colima"
docker.pkg-path = "docker-client"
kubectl.pkg-path = "kubectl"
gum.pkg-path = "gum"

[services]
colima.command = "colima start"
colima.is-daemon = true
colima.shutdown.command = "colima stop"

colima-k8s.command = '''
until colima status; do
  echo "colima-k8s >>> waiting for colima ..."
  sleep 3
done
colima k start
'''
colima-k8s.is-daemon = true
colima-k8s.shutdown.command = "colima k stop"

[hook]
on-activate = '''
if [[ "$FLOX_ACTIVATE_START_SERVICES" == "true" ]]; then
  gum style --border double --margin "1 2" --padding "1 4" \
    'Docker may take a few moments to start.' '' 'Once it starts, try it with:' '  docker run hello-world'
else
  if ! docker ps > /dev/null 2>&1; then
    gum style --border double --margin "1 2" --padding "1 4" \
      'Docker is not running.' '' 'You may need to start it using:' '  flox services start'
  fi
fi
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]


