#
# This is a Flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1), manifest.toml(5) for more information.
#
version = 1

[install]
ollama.pkg-path = "ollama"
tmux.pkg-path   = "tmux"
gum.pkg-path    = "gum"

[vars]
OLLAMA_TMUX_SESSION="ollama"

[profile]
zsh = '''
  autostart="$HOME/.config/ollama-env/autostart"
  choice=
  if [ ! -f "$autostart" ]; then
      echo "Would you like to start the Ollama service in tmux?"
      choice=$(gum choose "Always - start now & on future activations" "Yes - start now only" "No - do not start")
      if [ "${choice:0:1}" = "A" ]; then
          mkdir -p "$HOME"/.config/ollama-env
          echo "1" > "$autostart"
          echo
          echo "Machine will start automatically on next activation. To disable this, run:"
          echo "  rm $autostart"
      fi
  fi

  if [ -f "$autostart" ] || [ "${choice:0:1}" = "A" ] || [ "${choice:0:1}" = "Y" ] ; then
    instructionsFile=$(mktemp)
    echo > $instructionsFile
    echo "The ollama service is running in the top pane." >> $instructionsFile
    echo >> $instructionsFile
    echo "Use 'ollama pull' to download a model, e.g. 'ollama pull llama3'" >> $instructionsFile
    echo "Use 'ollama run' to run a model, e.g. 'ollama run llama3'" >> $instructionsFile
    echo "Use 'teardown' to kill the session" >> $instructionsFile

    # In case we're already running
    $FLOX_ENV/bin/tmux kill-session -t $OLLAMA_TMUX_SESSION

    # Create a new tmux session
    $FLOX_ENV/bin/tmux new-session -d -s $OLLAMA_TMUX_SESSION

    # Create a pane at the top
    $FLOX_ENV/bin/tmux split-window -v -t $OLLAMA_TMUX_SESSION
    $FLOX_ENV/bin/tmux resize-pane -t $OLLAMA_TMUX_SESSION:0.0 -y 7

    # Run the ollama servce in the top pane
    $FLOX_ENV/bin/tmux send-keys -t $OLLAMA_TMUX_SESSION:0.0 "ollama serve" Enter

    # Create an alias in the bottom pane
    # (and clear the screen so the user doesn't have to see it)
    $FLOX_ENV/bin/tmux send-keys -t $OLLAMA_TMUX_SESSION:0.1 "alias teardown='tmux kill-session -t " $OLLAMA_TMUX_SESSION "'" Enter

    # Provide some instructions for the user
    $FLOX_ENV/bin/tmux send-keys -t $OLLAMA_TMUX_SESSION:0.1 "alias instructions='command cat " $instructionsFile "'" Enter
    $FLOX_ENV/bin/tmux send-keys -t $OLLAMA_TMUX_SESSION:0.1 "instructions" ^L Enter

    # Attach to our session!
    $FLOX_ENV/bin/tmux attach-session -t $OLLAMA_TMUX_SESSION

    # Cause the Flox environment to exit once tmux is done
    exit # im dead
  fi
'''

bash = '''
  autostart="$HOME/.config/ollama-env/autostart"
  choice=
  if [ ! -f "$autostart" ]; then
      echo "Would you like to start the Ollama service in tmux?"
      choice=$(gum choose "Always - start now & on future activations" "Yes - start now only" "No - do not start")
      if [ "${choice:0:1}" = "A" ]; then
          mkdir -p "$HOME"/.config/ollama-env
          echo "1" > "$autostart"
          echo
          echo "Machine will start automatically on next activation. To disable this, run:"
          echo "  rm $autostart"
      fi
  fi

  if [ -f "$autostart" ] || [ "${choice:0:1}" = "A" ] || [ "${choice:0:1}" = "Y" ] ; then
    instructionsFile=$(mktemp)
    echo > $instructionsFile
    echo "The ollama service is running in the top pane." >> $instructionsFile
    echo >> $instructionsFile
    echo "Use 'ollama pull' to download a model, e.g. 'ollama pull llama3'" >> $instructionsFile
    echo "Use 'ollama run' to run a model, e.g. 'ollama run llama3'" >> $instructionsFile
    echo "Use 'teardown' to kill the session" >> $instructionsFile

    # In case we're already running
    $FLOX_ENV/bin/tmux kill-session -t $OLLAMA_TMUX_SESSION

    # Create a new tmux session
    $FLOX_ENV/bin/tmux new-session -d -s $OLLAMA_TMUX_SESSION

    # Create a pane at the top
    $FLOX_ENV/bin/tmux split-window -v -t $OLLAMA_TMUX_SESSION
    $FLOX_ENV/bin/tmux resize-pane -t $OLLAMA_TMUX_SESSION:0.0 -y 7

    # Run the ollama servce in the top pane
    $FLOX_ENV/bin/tmux send-keys -t $OLLAMA_TMUX_SESSION:0.0 "ollama serve" Enter

    # Create an alias in the bottom pane
    # (and clear the screen so the user doesn't have to see it)
    $FLOX_ENV/bin/tmux send-keys -t $OLLAMA_TMUX_SESSION:0.1 "alias teardown='tmux kill-session -t " $OLLAMA_TMUX_SESSION "'" Enter

    # Provide some instructions for the user
    $FLOX_ENV/bin/tmux send-keys -t $OLLAMA_TMUX_SESSION:0.1 "alias instructions='command cat " $instructionsFile "'" Enter
    $FLOX_ENV/bin/tmux send-keys -t $OLLAMA_TMUX_SESSION:0.1 "instructions" ^L Enter

    # Attach to our session!
    $FLOX_ENV/bin/tmux attach-session -t $OLLAMA_TMUX_SESSION

    # Cause the Flox environment to exit once tmux is done
    exit # im dead
  fi
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]


