version = 1

[install]
# That's literally it, that's all you need
qmk.pkg-path = "qmk"

[vars]

[hook]
on-activate = '''
echo ""
echo "     ╔═════════════════════════════════════╗"
echo "     ║                                     ║"
echo "     ║  Compile and flash your firmware:   ║"
echo "     ║  👉 qmk compile                     ║"
echo "     ║  👉 qmk flash                       ║"
echo "     ║                                     ║"
echo "     ╚═════════════════════════════════════╝"
echo ""
'''


[profile]

[services]

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
