## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1

[install]
ollama-ui.pkg-path = "nextjs-ollama-llm-ui"
ollama.pkg-path = "ollama"

[vars]
NEXT_PUBLIC_OLLAMA_URL="http://localhost:11434"

[services.ollama]
command="ollama serve"

[services.ollama-ui]
command='''
# wait for ollama to be ready
until ollama list; do sleep 1; done

export NEXT_CACHE_DIR="$FLOX_ENV_CACHE/next"
mkdir -p $NEXT_CACHE_DIR
nextjs-ollama-llm-ui
'''

[profile]
common = '''
  if ollama list >/dev/null 2>&1; then
    echo "🤖 Ollama service running"
    echo "🌐 Web interface running on port 3000"
  else
    echo "⛔️ Ollama service not available"
  fi
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux", "x86_64-darwin"]
cuda-detection = false
